# Generated by Django 4.2 on 2024-11-07 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='file',
            field=models.FileField(upload_to='arts/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mp4', 'mp3'], message='Arts doit etre soit musique .mp3 ou .mp4 soit image :. jpg ou .png soit vidéo .mp4')]),
        ),
    ]
