# Generated by Django 4.2 on 2024-11-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_alter_art_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
