# Generated by Django 4.2 on 2024-11-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_art_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
