# Generated by Django 4.2 on 2024-11-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0005_alter_art_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='reference',
        ),
    ]
