# Generated by Django 4.2.16 on 2024-11-14 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0006_remove_art_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='file',
            field=models.FileField(upload_to='arts/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'jfif', 'mp4', 'avi', 'mov', 'webm'], message='Le fichier doit être une vidéo (.avi, .mp4, .mov, .webm) ou une image (.jpg, .png, .gif, .jfif)')]),
        ),
        migrations.AlterField(
            model_name='art',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='art',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
