# Generated by Django 4.2 on 2024-11-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0007_alter_art_file_alter_art_id_alter_art_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
